
// This file would be auto-generated by Supabase CLI.
// For this example, we'll define a simplified version based on our schema.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// FIX: Changed interface to type to fix Supabase client type inference.
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          cargo: "admin" | "operador" | "motorista"
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          cargo: "admin" | "operador" | "motorista"
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          cargo?: "admin" | "operador" | "motorista"
        }
      }
      veiculos: {
        Row: {
          id: string
          placa: string
          modelo: string | null
          cor: string | null
          status: "aguardando_coleta" | "em_transito" | "no_patio" | "finalizado"
          lat: number | null
          lng: number | null
          codigo_infracao_ctb: string | null
          fotos_avaria_url: string[] | null
          proprietario_nome: string | null
          proprietario_telefone: string | null
          motorista_id: string | null
          created_at: string
          ano: number | null
          chassi: string | null
          renavam: string | null
          observacoes: string | null
          proprietario_cpf: string | null
          proprietario_cep: string | null
          proprietario_rua: string | null
          proprietario_bairro: string | null
          proprietario_numero: string | null
        }
        Insert: {
          id?: string
          placa: string
          modelo?: string | null
          cor?: string | null
          status?: "aguardando_coleta" | "em_transito" | "no_patio" | "finalizado"
          lat?: number | null
          lng?: number | null
          codigo_infracao_ctb?: string | null
          fotos_avaria_url?: string[] | null
          proprietario_nome?: string | null
          proprietario_telefone?: string | null
          motorista_id?: string | null
          created_at?: string
          ano?: number | null
          chassi?: string | null
          renavam?: string | null
          observacoes?: string | null
          proprietario_cpf?: string | null
          proprietario_cep?: string | null
          proprietario_rua?: string | null
          proprietario_bairro?: string | null
          proprietario_numero?: string | null
        }
        Update: {
          id?: string
          placa?: string
          modelo?: string | null
          cor?: string | null
          status?: "aguardando_coleta" | "em_transito" | "no_patio" | "finalizado"
          lat?: number | null
          lng?: number | null
          codigo_infracao_ctb?: string | null
          fotos_avaria_url?: string[] | null
          proprietario_nome?: string | null
          proprietario_telefone?: string | null
          motorista_id?: string | null
          created_at?: string
          ano?: number | null
          chassi?: string | null
          renavam?: string | null
          observacoes?: string | null
          proprietario_cpf?: string | null
          proprietario_cep?: string | null
          proprietario_rua?: string | null
          proprietario_bairro?: string | null
          proprietario_numero?: string | null
        }
      }
      movimentacoes: {
        Row: {
          id: string
          veiculo_id: string
          data_entrada: string | null
          data_saida: string | null
          valor_diaria: number
          total_pago: number | null
          forma_pagamento: string | null
          created_at: string
        }
        Insert: {
          id?: string
          veiculo_id: string
          data_entrada?: string | null
          data_saida?: string | null
          valor_diaria: number
          total_pago?: number | null
          forma_pagamento?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          veiculo_id?: string
          data_entrada?: string | null
          data_saida?: string | null
          valor_diaria?: number
          total_pago?: number | null
          forma_pagamento?: string | null
          created_at?: string
        }
      }
      financeiro: {
        Row: {
          id: string
          tipo: "entrada" | "saida"
          valor: number
          descricao: string | null
          data: string
          movimentacao_id: string | null
        }
        Insert: {
          id?: string
          tipo: "entrada" | "saida"
          valor: number
          descricao?: string | null
          data?: string
          movimentacao_id?: string | null
        }
        Update: {
          id?: string
          tipo?: "entrada" | "saida"
          valor?: number
          descricao?: string | null
          data?: string
          movimentacao_id?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      create_new_vehicle_collection: {
        Args: {
          p_placa: string
          p_modelo: string
          p_cor: string
          p_proprietario_nome: string
          p_proprietario_telefone: string
          p_ano: number
          p_chassi: string
          p_renavam: string
          p_observacoes: string
          p_proprietario_cpf: string
          p_proprietario_cep: string
          p_proprietario_rua: string
          p_proprietario_bairro: string
          p_proprietario_numero: string
        }
        Returns: undefined
      }
    }
    Enums: {
      user_role: "admin" | "operador" | "motorista"
      vehicle_status: "aguardando_coleta" | "em_transito" | "no_patio" | "finalizado"
      transaction_type: "entrada" | "saida"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
